### ISSUE TITLE
cannot break line

### ISSUE THREAD

**Issue by nkbai** [tani/markdown-it-mathjax3#56]
$$
h=H_1(m) \\
v=VRF_k(m)=h^k
$$

it's rendered to one line.

**Comment by Dragon1573** [comment]
I'm currently using [Mathjax3 Plugin for Github](https://chrome.google.com/webstore/detail/mathjax-3-plugin-for-gith/peoghobgdhejhcmgoppjpjcidngdfkod) in **Microsoft Edge**. This is how your equation looks like:

![image](https://user-images.githubusercontent.com/49941141/148648678-061a596b-bb6f-41af-b1c6-77309afebf9c.png)

Both of @tani's and @sritchie's plugin are using Mathjax3, so I think the rendered equation between them **should** looks the same.

You should write it as follows:

```latex
$$
\begin{align}
h=H_1(m) \\
v=VRF_k(m)=h^k
\end{align}
$$
```

$$
\begin{align}
h=H_1(m) \\
v=VRF_k(m)=h^k
\end{align}
$$

Now it should be in 2 lines.

**Comment by Dragon1573** [comment]
The correct LaTeX code of your target is:

```latex
$$
\begin{array}{c}
h=H_1(m) \\
v=VRF_k(m)=h^k
\end{array}
$$
```

<details>
<summary>Rendering Effects</summary>

![image](https://user-images.githubusercontent.com/49941141/148649138-762d4ddd-f26f-411e-a779-3ed8e80619df.png)

![image](https://user-images.githubusercontent.com/49941141/148649164-3bf84354-bc93-4825-8f8c-c9f31c1a0724.png)

</details>

**Comment by tani** [comment]
@Dragon1573 Thank you for the nice suggestion.

@nkbai His suggestion is the answer for you.
Please close this issue if you have no problem.

Cheers!
