### ISSUE TITLE
Other output options

### ISSUE THREAD

**Issue by AustenLamacraft** [tani/markdown-it-mathjax3#58]
It would be good to have output options other than SVG. Is there a fundamental reason not to allow the full range of output options from MathJax includig HTML and MathML?

**Comment by NeoNexusX** [comment]
> It would be good to have output options other than SVG. Is there a fundamental reason not to allow the full range of output options from MathJax includig HTML and MathML?

https://github.com/NeoNexusX/markdown-it-mathjax3-pro。you can try this project for html render
