### ISSUE TITLE
Accessibility for MathJax

### ISSUE THREAD

**Issue by ulfschneider** [tani/markdown-it-mathjax3#59]
Hi Taniguchi, recently I´ve started using your mathjax3 project within my 11ty-powered website. I´m wondering if it´s possible to activate accessibility features for the output that is produced by your plugin. Would you consider supporting accessibility? Or is it already possible but I didn´t found the correct way of activating it?
Best regards, Ulf

**Comment by tani** [comment]
I am sorry for the late response. I accepted your suggestion and have added the a11y support just now. Please update your package.json. The new version of this package will add the mml a11y annotation.

**Comment by ulfschneider** [comment]
Thank you very much.
